console.log("this is the second part")
console.log("I want to check a conflict")
console.log("I want to check another test")
console.log("This to check the pull request")
console.log("Before go to have lunch")
console.log("I need to go to my car")
console.log("I need to share my location")
